// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DatingSiteContext))]
    [Migration("20201230095959_addedsample")]
    partial class addedsample
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataLayer.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Noobs"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Pros"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Omegaluls"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Friend", b =>
                {
                    b.Property<int>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("FriendId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("StatusId");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            FriendId = 1,
                            CategoryId = 1,
                            ReceiverId = 2,
                            SenderId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            FriendId = 2,
                            CategoryId = 2,
                            ReceiverId = 3,
                            SenderId = 2,
                            StatusId = 2
                        },
                        new
                        {
                            FriendId = 3,
                            CategoryId = 1,
                            ReceiverId = 1,
                            SenderId = 3,
                            StatusId = 2
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Name = "Dota 2",
                            Publisher = "Valve"
                        },
                        new
                        {
                            GameId = 2,
                            Name = "CS:GO",
                            Publisher = "Valve"
                        },
                        new
                        {
                            GameId = 3,
                            Name = "PUBG",
                            Publisher = "Bluehole Corporation"
                        },
                        new
                        {
                            GameId = 4,
                            Name = "World of Warcraft",
                            Publisher = "Blizzard"
                        },
                        new
                        {
                            GameId = 5,
                            Name = "Among us",
                            Publisher = "InnerSloth"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "MOBA"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "FPS"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Explore"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "King of the hill"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "MMO"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Strategy"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Open world"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Content = "Hello muthafucka",
                            ReceiverId = 1,
                            SenderId = 2,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 21, DateTimeKind.Local).AddTicks(3650)
                        },
                        new
                        {
                            MessageId = 2,
                            Content = "Check this shit out",
                            ReceiverId = 3,
                            SenderId = 1,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(2487)
                        },
                        new
                        {
                            MessageId = 3,
                            Content = "SKKRTSKRRRT",
                            ReceiverId = 2,
                            SenderId = 1,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(2513)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityId = 1,
                            Name = "Swedish"
                        },
                        new
                        {
                            NationalityId = 2,
                            Name = "Norwegian"
                        },
                        new
                        {
                            NationalityId = 3,
                            Name = "Danish"
                        },
                        new
                        {
                            NationalityId = 4,
                            Name = "German"
                        },
                        new
                        {
                            NationalityId = 5,
                            Name = "English"
                        },
                        new
                        {
                            NationalityId = 6,
                            Name = "Spanish"
                        },
                        new
                        {
                            NationalityId = 7,
                            Name = "French"
                        },
                        new
                        {
                            NationalityId = 8,
                            Name = "American"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Personality", b =>
                {
                    b.Property<int>("PersonalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalityId");

                    b.ToTable("Personalities");

                    b.HasData(
                        new
                        {
                            PersonalityId = 1,
                            Description = "Cute"
                        },
                        new
                        {
                            PersonalityId = 2,
                            Description = "Narcissistic"
                        },
                        new
                        {
                            PersonalityId = 3,
                            Description = "Manipulative"
                        },
                        new
                        {
                            PersonalityId = 4,
                            Description = "Shy"
                        },
                        new
                        {
                            PersonalityId = 5,
                            Description = "Leader"
                        },
                        new
                        {
                            PersonalityId = 6,
                            Description = "Strategist"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            Name = "XBOX"
                        },
                        new
                        {
                            PlatformId = 2,
                            Name = "PS"
                        },
                        new
                        {
                            PlatformId = 3,
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Holy shit dude.",
                            ReceiverId = 1,
                            SenderId = 2,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(7557)
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Holy shit dude.",
                            ReceiverId = 2,
                            SenderId = 3,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(7763)
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Holy shit dude.",
                            ReceiverId = 3,
                            SenderId = 1,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(7772)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Description = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            Description = "Accepted"
                        },
                        new
                        {
                            StatusId = 3,
                            Description = "Blocked"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<int>("PersonalityId")
                        .HasColumnType("int");

                    b.Property<string>("PreferedLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PersonalityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Active = true,
                            Age = 28,
                            FirstName = "Simon",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Bernsdorff Wallstedt",
                            Mail = "simon.bernsdorff-wallstedt@dating.com",
                            NationalityId = 1,
                            Online = false,
                            PersonalityId = 1,
                            PreferedLanguage = "Swedish"
                        },
                        new
                        {
                            UserId = 2,
                            Active = true,
                            Age = 27,
                            FirstName = "Lukas",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Brolin",
                            Mail = "lukas.brolin@dating.com",
                            NationalityId = 1,
                            Online = false,
                            PersonalityId = 2,
                            PreferedLanguage = "Swedish"
                        },
                        new
                        {
                            UserId = 3,
                            Active = true,
                            Age = 27,
                            FirstName = "Filip",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Johansson",
                            Mail = "filip.johansson@dating.com",
                            NationalityId = 1,
                            Online = false,
                            PersonalityId = 3,
                            PreferedLanguage = "Swedish"
                        },
                        new
                        {
                            UserId = 4,
                            Active = true,
                            Age = 34,
                            FirstName = "Magnus",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Fredriksson",
                            Mail = "magnus.fredriksson@dating.com",
                            NationalityId = 1,
                            Online = false,
                            PersonalityId = 4,
                            PreferedLanguage = "English"
                        },
                        new
                        {
                            UserId = 5,
                            Active = true,
                            Age = 22,
                            FirstName = "Didrik",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Hjelm",
                            Mail = "didrik.hjelm@dating.com",
                            NationalityId = 2,
                            Online = false,
                            PersonalityId = 2,
                            PreferedLanguage = "Norwegian"
                        },
                        new
                        {
                            UserId = 6,
                            Active = true,
                            Age = 25,
                            FirstName = "Selma",
                            Gender = "Female",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Nordheim",
                            Mail = "selma.nordheim@dating.com",
                            NationalityId = 2,
                            Online = false,
                            PersonalityId = 5,
                            PreferedLanguage = "Norwegian"
                        },
                        new
                        {
                            UserId = 7,
                            Active = true,
                            Age = 27,
                            FirstName = "Kassandra",
                            Gender = "Female",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Lökholm",
                            Mail = "kassandra.Lökholm@dating.com",
                            NationalityId = 1,
                            Online = false,
                            PersonalityId = 1,
                            PreferedLanguage = "Swedish"
                        },
                        new
                        {
                            UserId = 8,
                            Active = true,
                            Age = 31,
                            FirstName = "Kent",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Andersson",
                            Mail = "kent.andersson@dating.com",
                            NationalityId = 1,
                            Online = false,
                            PersonalityId = 5,
                            PreferedLanguage = "Swedish"
                        },
                        new
                        {
                            UserId = 9,
                            Active = true,
                            Age = 41,
                            FirstName = "Sebastian",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Vettel",
                            Mail = "sebastian.vettel@dating.com",
                            NationalityId = 4,
                            Online = false,
                            PersonalityId = 3,
                            PreferedLanguage = "German"
                        },
                        new
                        {
                            UserId = 10,
                            Active = true,
                            Age = 38,
                            FirstName = "Nico",
                            Gender = "Male",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Rosberg",
                            Mail = "nico.rosberg@dating.com",
                            NationalityId = 4,
                            Online = false,
                            PersonalityId = 3,
                            PreferedLanguage = "German"
                        },
                        new
                        {
                            UserId = 11,
                            Active = true,
                            Age = 30,
                            FirstName = "Emma",
                            Gender = "Female",
                            ImgUrl = "Images/User/User.jpg",
                            LastName = "Watson",
                            Mail = "emma.watson@dating.com",
                            NationalityId = 5,
                            Online = false,
                            PersonalityId = 4,
                            PreferedLanguage = "English"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            ReceiverId = 1,
                            SenderId = 1,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(9034)
                        },
                        new
                        {
                            VisitId = 2,
                            ReceiverId = 2,
                            SenderId = 3,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(9377)
                        },
                        new
                        {
                            VisitId = 3,
                            ReceiverId = 3,
                            SenderId = 2,
                            TimeStamp = new DateTime(2020, 12, 30, 10, 59, 59, 23, DateTimeKind.Local).AddTicks(9385)
                        });
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<int>("GamesGameId")
                        .HasColumnType("int");

                    b.Property<int>("GenresGenreId")
                        .HasColumnType("int");

                    b.HasKey("GamesGameId", "GenresGenreId");

                    b.HasIndex("GenresGenreId");

                    b.ToTable("GameGenre");

                    b.HasData(
                        new
                        {
                            GamesGameId = 1,
                            GenresGenreId = 1
                        },
                        new
                        {
                            GamesGameId = 1,
                            GenresGenreId = 2
                        },
                        new
                        {
                            GamesGameId = 3,
                            GenresGenreId = 4
                        },
                        new
                        {
                            GamesGameId = 4,
                            GenresGenreId = 5
                        },
                        new
                        {
                            GamesGameId = 4,
                            GenresGenreId = 7
                        },
                        new
                        {
                            GamesGameId = 4,
                            GenresGenreId = 3
                        });
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.Property<int>("GamesGameId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformsPlatformId")
                        .HasColumnType("int");

                    b.HasKey("GamesGameId", "PlatformsPlatformId");

                    b.HasIndex("PlatformsPlatformId");

                    b.ToTable("GamePlatform");

                    b.HasData(
                        new
                        {
                            GamesGameId = 1,
                            PlatformsPlatformId = 3
                        });
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.Property<int>("GamesGameId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("GamesGameId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("GameUser");

                    b.HasData(
                        new
                        {
                            GamesGameId = 1,
                            UsersUserId = 3
                        });
                });

            modelBuilder.Entity("GenreUser", b =>
                {
                    b.Property<int>("GenresGenreId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("GenresGenreId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("GenreUser");

                    b.HasData(
                        new
                        {
                            GenresGenreId = 3,
                            UsersUserId = 2
                        });
                });

            modelBuilder.Entity("PlatformUser", b =>
                {
                    b.Property<int>("PlatformsPlatformId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("PlatformsPlatformId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("PlatformUser");

                    b.HasData(
                        new
                        {
                            PlatformsPlatformId = 2,
                            UsersUserId = 3
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Friend", b =>
                {
                    b.HasOne("DataLayer.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", "Receiver")
                        .WithMany("Friends")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", "Sender")
                        .WithMany("Users")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataLayer.Models.Message", b =>
                {
                    b.HasOne("DataLayer.Models.User", "Receiver")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DataLayer.Models.Post", b =>
                {
                    b.HasOne("DataLayer.Models.User", "Receiver")
                        .WithMany("PostsReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", "Sender")
                        .WithMany("PostsSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DataLayer.Models.User", b =>
                {
                    b.HasOne("DataLayer.Models.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Personality", "Personality")
                        .WithMany()
                        .HasForeignKey("PersonalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nationality");

                    b.Navigation("Personality");
                });

            modelBuilder.Entity("DataLayer.Models.Visit", b =>
                {
                    b.HasOne("DataLayer.Models.User", "Receiver")
                        .WithMany("Visitors")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", "Sender")
                        .WithMany("MyVisits")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("DataLayer.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.HasOne("DataLayer.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameUser", b =>
                {
                    b.HasOne("DataLayer.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreUser", b =>
                {
                    b.HasOne("DataLayer.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformUser", b =>
                {
                    b.HasOne("DataLayer.Models.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataLayer.Models.User", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("MyVisits");

                    b.Navigation("PostsReceived");

                    b.Navigation("PostsSent");

                    b.Navigation("Users");

                    b.Navigation("Visitors");
                });
#pragma warning restore 612, 618
        }
    }
}
